config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# for board-list
  resources :user, only: [:show]
# board action
  resources :boards, only: [:index, :create, :edit, :update] do
# todo action
    resources :todos, only: [:index, :create, :update, :destroy]
  end
# search todo card
  get '/todos/search', to: 'todos#search'
# index
  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :user_boards
  has_many :users, through: :user_boards
  has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_boards
  has_many :boards, through: :user_boards
  has_many :todos
end

app/models/user_board.rb
class UserBoard < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
# add vatidation "name"
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :board_set, only: [:edit, :update]
  before_action :newBoard_setBoards, only: [:index, :edit]

  def index
  end

  def create
    @board = Board.new(board_params)
    @board.save
    @user_boards = UserBoard.new(user_id: current_user.id, board_id: @board.id)
    @user_boards.save
  end

  def edit
    @users = @board.users
  end

  def update
    @board.update(board_params)
    redirect_to edit_board_path(@board), notice: 'ボード名を編集しました'
  end


  private
  def board_params
    params.require(:board).permit(:name, { :user_ids => [] })
  end

  def board_set
    @board = Board.find(params[:id])
  end

  def newBoard_setBoards
    @board_new = Board.new
    @boards = current_user.boards
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :variable_sets, except: [:search]
  before_action :set_newBoard, only: [:index, :search]
  # before_action :todo_params
  def index
  # set header variable for header
    @todo = Todo.new
  # set board todos
    @todos = @board.todos.includes(:user)
  # set cards belongs to each list
    @list_1 = @todos.where(list: 1)
    @list_2 = @todos.where(list: 2)
    @list_3 = @todos.where(list: 3)
  end

  def create
    @todo = @board.todos.new(todo_params)

    if @todo.save
      respond_to do |format|
        format.html {redirect_to board_todos_path(params[:board_id]), notice: "カードが追加されました"}
        format.json
      end
    else
      @todos = @board.todos.includes(:user)
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to board_todos_path(@board), notice: 'カードを編集しました'
    else
      render :index
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to board_todos_path(@board)
  end

  def search
  # set variable for search view
    @boards = current_user.boards
  # set search todos n boards
    @search_todos = current_user.todos.where('text LIKE(?)', "%#{params[:keyword]}%")
    @search_boards = @boards.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

  private
  def variable_sets
    # for create board
    @board = Board.find(params[:board_id])
    # get current_users boards
    @boards = current_user.boards
  end

  def todo_params
    params.require(:todo).permit(:text, :limit, :check, :list).merge(user_id: current_user.id)
  end

  def set_newBoard
    @board_new = Board.new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  # for header create new action in boards controller
    @board_new = Board.new
  # for show current_user board list
    @boards = current_user.boards
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
= render 'todos/header'
.contents
  .contents__cover
    .boards-list-cover
      %h2
        #{@board.name}の編集
      = form_for @board, method: :patch do |f|
        = f.label :ボード名の変更
        = f.text_field :name
        = f.submit '変更'
      - @users.each do |user|
        = form_for user, method: :patch do |f|
          = f.label :メンバーの変更
          = f.text_field :name
          = f.submit '変更'
= render 'todos/footer'
/ change to ajax after that

app/views/boards/index.html.haml
= render 'todos/header'
.contents
  .contents__cover
    .contents__cover__left.list-cover
      .todo-card-default
        %p.info-text
          新規の方はボードの作成を右上のボタンから、
          %br
          既存ユーザーの方は左上のボードリストからボードを選択か、
          %br
          新たに作成しましょう!!
    .contents__cover__center.list-cover
    .contents__cover__right.list-cover
= render 'todos/footer'

app/views/boards/new.html.haml
/ 仮作成、仕様変更？
= render 'todos/header'
.contents
  .contents__cover
= render 'todos/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/todos/_footer.html.haml
.footer
  .footer__cover
    %p
      copyright...

app/views/todos/_header.html.haml
.header
  .header__cover.sub-border
    .header__cover__left.sub-border
      .board-list.sub-border
        %p.btn-text
          ボードリスト
      .search-box.sub-border
        = form_tag(todos_search_path, method: :get) do
          = text_field_tag :keyword, '', class: "search_todos", placeholder: "検索ワード"
          = button_tag type: "submit", class: "button" do
            .fa.fa-search.fa-2x.header-search-icon
    %h2.header-board
    .header__cover__right.sub-border
      .add-boader.sub-border
        = fa_icon "plus", class: "fa-2x header-user-icon"
      .user-profile.sub-border
        = fa_icon "user", class: "fa-2x header-user-icon"
  %ul.header__board-list.sub-border.text-inline
    - @boards.each do |board|
      %li
        = link_to  board_todos_path(board_id: board.id) do
          = board.name
  .header__create-board.sub-border.text-inline
    = form_for(@board_new, url: boards_path, method: :post) do |f|
      = f.text_field :name, autocomplete: "off", placeholder: 'ボードタイトル', size: "15"
      = f.submit "ボードを作成", redirect_to: root_path
  %ul.header__profile-list.sub-border.text-inline
    %li
      = link_to 'Edit user profile', edit_user_registration_path
    %li
      = link_to 'Bord list',  user_path(current_user)
    %li
      = link_to 'Log out', destroy_user_session_path, method: :delete

app/views/todos/_todo-card.html.haml
.todo-card{"data-todo-id": todo.id}
  = form_for [@board, todo], html:{id: "ajax-todo"}, method: :patch do |f|
    = f.check_box :check, class: "checkbox"
    = f.date_field :limit, class: "limit-date"
    = f.text_area :text, class: "todo-text"
    = f.submit "修正", class: "submit-btn"
    = link_to board_todo_path(id: todo.id), method: :delete do
      .fa.fa-times.fa-lg

app/views/todos/index.html.haml
= render 'header'
.contents
  .contents__cover
    .contents__cover__left.list-cover
      - @list_1.each do |todo|
        = render 'todo-card', {todo: todo}
      .todo-card-new.js-1
        = form_for [@board, @todo], html:{id: "ajax-todo"} do |f|
          = f.hidden_field :list, value: "1"
          = f.check_box :check, class: "checkbox"
          = f.date_field :limit, class: "limit-date"
          = f.text_area :text, class: "todo-text"
          = f.submit "追加", class: "submit-btn"
          = link_to board_todos_path do
            .fa.fa-times.fa-lg
      .todo-btn.list-1
        %p.btn-text
          カードを追加
    .contents__cover__center.list-cover
      - @list_2.each do |todo|
        = render 'todo-card', {todo: todo}
      .todo-card-new.js-2
        = form_for [@board, @todo], html:{id: "ajax-todo"} do |f|
          = f.hidden_field :list, value: "2"
          = f.check_box :check, class: "checkbox"
          = f.date_field :limit, class: "limit-date"
          = f.text_area :text, class: "todo-text"
          = f.submit "追加", class: "submit-btn"
          = link_to board_todos_path do
            .fa.fa-times.fa-lg
      .todo-btn.list-2
        %p.btn-text
          カードを追加
    .contents__cover__right.list-cover
      - @list_3.each do |todo|
        = render 'todo-card', {todo: todo}
      .todo-card-new.js-3
        = form_for [@board, @todo], html:{id: "ajax-todo"} do |f|
          = f.hidden_field :list, value: "3"
          = f.check_box :check, class: "checkbox"
          = f.date_field :limit, class: "limit-date"
          = f.text_area :text, class: "todo-text"
          = f.submit "追加", class: "submit-btn"
          = link_to board_todos_path do
            .fa.fa-times.fa-lg
      .todo-btn.list-3
        %p.btn-text
          カードを追加
= render 'footer'

app/views/todos/search.html.haml
= render 'header'
.contents
  .contents__cover
    .boards-list-cover
      %ul
        %p
          #{params[:keyword]}の検索結果
        - @search_boards.each do |board|
          %li
            = link_to "Board: #{board.name}", board_todos_path(board)
        - @search_todos.each do |todo|
          %li
            = link_to "Todo: #{truncate(todo.text, length: 15)}, Board: #{todo.board.name}", board_todos_path(todo.board)
= render 'footer'

app/views/user/show.html.haml
= render 'todos/header'
.contents
  .contents__cover
    .boards-list-cover
      %ul
        %p
          #{current_user.name}さんのボードリスト
        - @boards.each do |board|
          %li
            = link_to "#{board.name}", board_todos_path(board), class: "board-list-height"
            %print
              Member:
            - board.users.each do |user|
              = user.name
            = link_to "edit", edit_board_path(board), class: "board-list-height"
= render 'todos/footer'